# Common python container setup for jobs
.python-container:
  image: $PYTHON_IMAGE
  cache:
    paths:
      - .cache/pip
      - .cache/pre-commit
  before_script:
    - python --version ; pip --version
    - pip install --upgrade pip
    - pip install uv --upgrade
    - uv sync --prerelease=allow
    - source .venv/bin/activate
