# Common python container setup for jobs
.python-container:
  image: $PYTHON_IMAGE
  cache:
    paths:
      - .cache/pip
      - .cache/pypoetry
      - .cache/pre-commit
  before_script:
    - python --version ; pip --version
    - pip install --upgrade pip
    - pip install poetry --upgrade
    - poetry install
    - source `poetry env info --path`/bin/activate
