# this sample configuration demonstrates setup for New York City Subway
# arrival and alerts, configure it appropriately using the gtfs_static_data

gtfs_realtime:
  # sign up for an API key at https://api.mta.info/
  api_key: !secret ny_mta_api_key
  url_endpoints:
    - "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-l"
    - "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/camsys%2Fsubway-alerts"
  # static data for Subways updates less frequently
  # use the URLs for regular and supplemented GTFS data for mostly complete schedules
  gtfs_static_data:
    - "http://web.mta.info/developers/data/nyct/subway/google_transit.zip"
    - "http://web.mta.info/developers/files/google_transit_supplemented.zip"
  # route bullets are provided in resources/NYCT_Bullets with
  route_icons: /local/NYCT_Bullets

# the sensor config below will set up arrival notifications for
# northbound and southbound 14th St-Union Sqare L trains as well
# as service alerts for L trains

sensor northbound union-sq:
  - platform: gtfs_realtime
    # stop_id can be found in gtfs_static_data stops.txt
    stop_id: L03N

sensor southbound union-sq:
  - platform: gtfs_realtime
    stop_id: L03S

binary_sensor L alert:
  - platform: gtfs_realtime
    # route_id can be found in gtfs_static_data routes.txt
    route_id: L
