stages:
  - lint
  - test
  - trigger-deploy

variables:
  PYTHON_VERSION: 3.13
  UV_VERSION: 0.5.22
  BASE_LAYER: bookworm
  PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
  UV_CACHE_DIR: $CI_PROJECT_DIR/.cache/uv

default:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    - key:
        files:
        - uv.lock
      paths:
      - $UV_CACHE_DIR
    - key:
        files:
        - .pre-commit-config.yaml
      paths:
      - $PRE_COMMIT_HOME
  before_script:
    - python --version ; pip --version ; uv --version
    - uv sync --all-groups --prerelease=allow
    - source .venv/bin/activate
  after_script:
    - uv cache prune --ci

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

secret_detection:
  inherit:
    default: false
  stage: lint

check_formatting:
  stage: lint
  cache:
    paths:
      - $PRE_COMMIT_HOME
  script:
    - SKIP=hassfest,pytest pre-commit run --all-files

hassfest:
  stage: lint
  inherit:
    default: false
  image: 
    name: ghcr.io/home-assistant/hassfest
    entrypoint: [""]
  script:
    - /usr/src/homeassistant/script/hassfest/docker/entrypoint.sh

pytest:
  stage: test
  variables:
    TEST_RESULTS_FILE: "test_results.xml"
    TEST_COVERAGE_FILE: "coverage.xml"
  script:
    - pytest --cov=homeassistant-gtfs-realtime --cov-report term tests/ --cov-report xml:$TEST_COVERAGE_FILE --junitxml $TEST_RESULTS_FILE
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    paths:
      - $TEST_RESULTS_FILE
      - $TEST_COVERAGE_FILE
      - tests/**/*.ambr
    reports:
      junit: $TEST_RESULTS_FILE
      coverage_report:
        coverage_format: cobertura
        path: $TEST_COVERAGE_FILE

# Launch deployment from complementary deployment repo
deploy_job:
  stage: trigger-deploy
  trigger:
    include:
      - project: bcpearce/homeassistant-gtfs-realtime-deploy
        ref: main
        file: /.gitlab-ci/deploy.yml
