name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  uv-feed-compatibility:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
        with: 
          version: "0.7.13"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: "Install the project"
        run: uv sync --locked --all-extras --dev
      - name: "Check Feed Compatibility"
        run: python hooks/check_feed_compatibility.py custom_components/gtfs_realtime/feeds.json -f md >> $GITHUB_STEP_SUMMARY


