name: Run tests on upgraded packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [test-upgrade]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  uv-pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.11.1
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: "Install the project"
        run: uv sync --upgrade --all-extras --dev
      - name: "Run tests"
        run: |
          uv run pytest tests
